ARG ELASTICSEARCH_VERSION
FROM docker.elastic.co/logstash/logstash:${ELASTICSEARCH_VERSION}

USER root

RUN yum install -y wget

RUN wget -O /etc/yum.repos.d/wireshark.repo https://www.1310nm.net/repository/CentOS/7/wireshark.repo
RUN yum -y install epel-release
RUN yum -y update
RUN yum install -y libnghttp2 lz4
RUN yum install -y wireshark-qt

ADD pipeline-logstash.conf /usr/share/logstash/pipeline/logstash.conf

ADD pcap.sh /pcap.sh

CMD /pcap.sh
